workspace 'Bonfire'

def shared_pods
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
end

target ‘RxSugar’ do
  project ‘../RxSugar/RxSugar’
   use_frameworks!
  shared_pods
end

target 'Bestiary' do
  project ‘../Bestiary/Bestiary’
   use_frameworks!
  shared_pods
end

target 'Bonfire' do
  project ‘Bonfire'
  use_frameworks!

  shared_pods

  target 'BonfireTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
